name: Deploy to GitHub Pages

on:
  push:
    branches: [ hw-4 ]
  workflow_dispatch:

# Добавляем явные permissions
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Копируем frontend файлы в папку для деплоя
      - name: Copy frontend files
        run: |
          mkdir -p ./dist
          cp -r src/frontend/* ./dist/
      
      # Деплоим на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages 